Linear equations with python

In [17]:
#sloving linear equations 
from sympy import symbols, simplify

b1, b2, b0 = symbols('b1 b2 b0')
eq1 = (2*23*(23*b1+0.5*b2+b0-55)+2*35*(35*b1+b2+b0-100)+2*18*(18*b1+b0-45))/3
eq2 = (2*0.5*(23*b1+0.5*b2+b0-55)+2*(35*b1+b2+b0-100))/3
eq3 = (2*(23*b1+0.5*b2+b0-55)+2*(35*b1+b2+b0-100)+2*(18*b1+b0-45))/3
print(eq1)
print(eq2)
print(eq3)

152*b0/3 + 4156*b1/3 + 31.0*b2 - 11150/3
b0 + 31.0*b1 + 0.833333333333333*b2 - 85.0
2*b0 + 152*b1/3 + b2 - 400/3


In [15]:
import numpy as np
syst = np.array([[152/3, 4156/3, 31],
                [1, 31, 0.833333],
                [2, 152/3, 1]])
swob = np.array([11150/3, 85, 400/3])
try:
    answ = np.linalg.solve(syst, swob)
    print(answ)
    
except np.linalg.LinAlgError:
    print("np solution/ infinite solution")

[-45.00051062   5.00003123 -30.00056083]


matrix with python

In [20]:
a = np.array([[1,2,3],[3,4,5]], dtype = np.complex128)
a #complex128 - data type for complex values (only 128 bits)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j, 5.+0.j]])

In [22]:
#add martix
m1 = np.array([[2,3,4],[1,2,3]])
m2 = np.array([[1,2,3], [1,1,1]])
print(m1+m2, "\n")
print(m1-m2) #if size different - Vlaue error

[[3 5 7]
 [2 3 4]] 

[[1 1 1]
 [0 1 2]]


In [24]:
mn1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mn2 = np.array([[1],[2],[3]])
np.dot(mn1,mn2) #matrix multiplication
#np.dot(mn2, mn1) - value error (this operation is not defined)

array([[14],
       [32],
       [50]])

In [25]:
#transpose 
c = np.array([[1,1,1,1],[2,2,2,2]])
c.T

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [26]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#inverse matrix
a = np.array([[5,5,6],[7,8,4],[1,2,3]])
np.linalg.inv(a) #numpy function for inverse function

array([[ 0.51612903, -0.09677419, -0.90322581],
       [-0.5483871 ,  0.29032258,  0.70967742],
       [ 0.19354839, -0.16129032,  0.16129032]])

In [26]:
#find a coefficients for linear regression model using formula
# b = (x.T*x)^-1 * x.T * y
import numpy as np
x = np.array([[23,0.5,1],[35,1,1],[18,0,1]])
y = np.array([55,100,45])

step1 = np.linalg.inv(np.dot(x.T, x))
step2 = np.dot(step1_inverse, x.T)
rez = np.dot(step2, y)

In [27]:
rez

array([  5., -30., -45.])